### PR TITLE
async-http-client-1.9

### PR DESCRIPTION
**Pull request by agourlay**
This PR upgrades the project to use async-http-client-1.9.x.

Things to inspect:
- ```NettyAsyncHttpProviderConfig.SOCKET_CHANNEL_FACTORY``` is not present anymore
- ```EntityWriter``` as been completely replaced by ```BodyGenerator```
- I had to modified the jsoupSpec as ```localhost.url``` now ends with ```/```

I also upgraded a few other dependencies on the way :bowtie:

### CODE REVIEW

**Comment by agourlay** [comment]
async-http-client-1.9.x dropped JDK6 support so I need to reflect that change in .travis.yml

**Comment by yanns** [comment]
This change is blocking us from migrating AsyncHttpClient.
It'd great if somebody could review it.
Thx in advance!

**Comment by agourlay** [comment]
Thank you for taking the time to have a look at this PR.
To be honest I was not expecting this anymore :astonished:

**Comment by n8han** [comment]
¯\_(ツ)_/¯

**Pull request merged**
