### PR TITLE
update scala-xml

### PR DESCRIPTION
**Pull request by yanns**
fix https://github.com/dispatch/reboot/issues/235
lift-json also depends on scala-xml 1.2.
lift-json is not maintained anymore.
I propose to remove the module.

### CODE REVIEW

**Comment by yanns** [comment]
@farmdawgnation can you authorize the PR checks?

**Comment by farmdawgnation** [comment]
Yeah. I’ll have a look today. On Jan 30, 2023, at 3:38 AM, Yann Simon ***@***.***> wrote:﻿
@farmdawgnation can you authorize the PR checks?

**Comment by farmdawgnation** [comment]
PR checks are authorized. Will noodle on how I feel about actually pulling the plug on lift-json support but alas, I'm also one of the key maintainers over there and I'm not sure it's aged particularly well.

**Comment by farmdawgnation** [comment]
Checks have all passed... give me a bit to think about the lift-json question.

**Review by farmdawgnation — APPROVED** [review]
Approved, though I think I'll have to consider this a major version bump.

**Pull request merged**
