### PR TITLE
Upgrade to AHC 2.4.7 for Dispatch 1.0

### PR DESCRIPTION
**Pull request by farmdawgnation**
Upgrades to the latest AHC version and makes the required API changes.

### CODE REVIEW

**Comment by simong** [comment]
Hey @farmdawgnation, any chance you could publish a 1.0.0-SNAPSHOT for this? We're keen to test the new AHC release.

**Comment by farmdawgnation** [comment]
@simong It's now live on Sonatype Snapshots. Please do let me know how it goes. :)

**Comment by simong** [comment]
@farmdawgnation, so far this has been beneficial to us (especially with regards to SSL handling), many thanks!

As we start prepping for production, we'd like to start binding to something a bit more stable than a snapshot. We have our own ivy repository where we could publish a fixed version of dispatch into, but before we make that jump I wanted to double-check how far off the 1.0.0 release was. If you're planning to release it in the coming week or so, we can easily wait for that. Do you have an estimate that you could share for when 1.0.0 would be out?

**Comment by farmdawgnation** [comment]
I’m going to ship an M1 toward the end of this week or early next. M2 will
come a few weeks later with a final 1.0 build in July. There may be some
minor breaking changes before I declare RC, but most of what I want to do
is version bump dependencies. Lift is scheduled to release 3.3 final at the
start of July and I’d like to get that version of lift-json in our final
1.0 build if possible.

**Comment by farmdawgnation** [comment]
@simong 1.0.0-M1 has been released!

**Pull request merged**
