### PR TITLE
Ahc3

### PR DESCRIPTION
**Pull request by maiflai**

### CODE REVIEW

**Comment by farmdawgnation** [comment]
Am I understanding correctly that the removal of the oauth v1 bits are unrelated to the AHC upgrade? Or is there some reason these things are linked?

**Comment by maiflai** [comment]
sorry - I think https://github.com/AsyncHttpClient/async-http-client/pull/1902 is the removal of oauth from AHC?

**Comment by farmdawgnation** [comment]
Ah fair enough.

**Comment by farmdawgnation** [comment]
This looks good to me. We'll drop support for Java 8 as a part of this so I'll need to do some version number shuffling, but I think this will work.

**Comment by maiflai** [comment]
great, thanks very much

**Pull request merged**
