### PR TITLE
Upgrade to AsyncHttpClient 2.0.32

### PR DESCRIPTION
**Pull request by fbascheper**
First attempt to upgrade to AHC 2.0.32. 
Tests don't work right now, as stated in [PR#139](https://github.com/dispatch/reboot/pull/139).

Edits from maintainers are enabled, so you can update the PR to your unfiltered 0.8.4 cross built against scala 2.12.2. 

After that I'll try to fix up the tests again (if necessary).

### CODE REVIEW

**Comment by farmdawgnation** [comment]
Alright, I've pushed my commit updating the build. Locally they passed but Travis choked on trying to clone the repo. Heh. Going to try kicking it off again.

**Comment by farmdawgnation** [comment]
Bah humbug. There's one failing test and only in Scala 2.11:

```
[error] Error: Total 37, Failed 0, Errors 1, Passed 36
[error] Error during tests:
[error] 	dispatch.oauth.spec.ExchangeSpecification
```

**Comment by farmdawgnation** [comment]
Hm, it actually looks like this test may be intermittent.... most of the time it passes and at other times it doesn't. For example:

```
Exception: java.lang.IllegalArgumentException: Header value contains a prohibited character '\v'
```

Perhaps we should consider limiting the things that this test might produce to random things in the alphanumeric scope?

**Comment by farmdawgnation** [comment]
Hm, on second inspection I think I'm misunderstanding the test output. Will def want you to have a look here. Something funky is up.

**Comment by fbascheper** [comment]
I've reproduced this as a bug in AHC / Netty.

**Comment by farmdawgnation** [comment]
Well at least it ain't our fault. 😅 

I'll follow along with the AHC/netty issue and see what the timeline for a fix look like.

**Comment by fbascheper** [comment]
I've updated the test so that it only uses alphanumeric characters anymore. This ensures we're no longer hitting the upstream bugs in Netty / AHC 2.0.32.

**Comment by fbascheper** [comment]
The upstream bug is fixed in AHC 2.0.33. Using a local snapshot build of AHC the original test no longer fails intermittently.

**Pull request merged**
